version: '3'

services:
  mariadb:
    build: 
      context: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:inception
    env_file:
      - .env
    restart: always
    volumes:
      - database:/var/lib/mysql/
    networks:
      - mybridge
  wordpress:
    build: 
      context: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:inception
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb
      - nginx
    volumes:
      - wordpress:/var/www/html/
    networks:
      - mybridge
  nginx:
    build: 
      context: ./requirements/nginx
    container_name: nginx
    image: nginx:inception
    env_file:
      - .env
    restart: always
    volumes:
      - wordpress:/var/www/html/
    ports:
      - '443:443'
    networks:
      - mybridge
volumes:
  wordpress:
    driver: local
    driver_opts: 
      type: none
      device: /home/abelfany/data/wordpress
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/abelfany/data/database
      o: bind

networks:
  mybridge:
    driver: bridge

